services:
    mukadi.chart.default_definition_provider:
        class: Mukadi\ChartJSBundle\Provider\DefinitionProvider
        public: true
    mukadi.chart.factory:
        class: Mukadi\ChartJSBundle\Factory\ChartFactory
        public: true
        arguments: ["@doctrine.orm.entity_manager", "@mukadi.chart.default_definition_provider"]
    mukadi.chart.twig_extension:
        class: Mukadi\ChartJSBundle\Twig\ChartJSExtension
        public: true
        tags:
            - { name : twig.extension }
    Mukadi\ChartJSBundle\Factory\ChartFactory:
        alias: mukadi.chart.factory
    Mukadi\ChartJSBundle\Provider\DefinitionProvider:
        alias: mukadi.chart.default_definition_provider